- hosts: localhost
  become: false
  connection: local
  tasks:
  - name: Install htop
    homebrew: name=htop

  - name: Install bat
    homebrew: name=bat

  - name: Install tmux
    homebrew: name=tmux

