- hosts: all
  gather_facts: no
  become: false
  connection: local
  pre_tasks:
    - name: update repositories
      tags: always
      homebrew:
        update_homebrew: yes
      changed_when: false

  tasks:
    - include: tasks/base.yml
      tags: always

    - name: Optional tasks
      tags: never, full
      block:
      - include: tasks/develop.yml
        tags: devl

      - include: tasks/office.yml
        tags: office

      - include: tasks/security.yml
        tags: security

      - include: tasks/v12n.yml
        tags: v12n
