- hosts: localhost
  become: false
  connection: local
  pre_tasks:
    - name: update repositories
      homebrew:
        update_homebrew: yes
      changed_when: false

  tasks:
    - include: tasks/base.yml
    - include: tasks/develop.yml
      when: develop is defined or all is defined

