- hosts: localhost
  become: false
  connection: local
  pre_tasks:
    - name: update repositories
      homebrew:
        update_homebrew: yes
      changed_when: false

  tasks:
    - include: tasks/base.yml
    - include: tasks/develop.yml
      when: develop is defined or all is defined
    - include: tasks/office.yml
      when: office is defined or all is defined
    - include: tasks/security.yml
      when: security is defined or all is defined
    - include: tasks/v12n.yml
      when: v12n is defined or all is defined
