- name: Install virtualisation packages
  homebrew: name={{ item }}
  with_items:
    - kubernetes-cli

- name: Install virtualisation cask packages
  homebrew_cask: name={{ item }}
  with_items:
    - vagrant
    - virtualbox
    - virtualbox-extension-pack
    - vmware-fusion
